name: 定时生成并推送 ros-dpbr-CT-CMCC.rsc 到 main

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Make script executable
        run: chmod +x gen_ros_dpbr.sh

      - name: Run script
        run: ./gen_ros_dpbr.sh

      - name: Set up git for push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push to main
        run: |
          git add ros-dpbr-CT-CMCC.rsc
          git commit -m "自动生成最新 ros-dpbr-CT-CMCC.rsc [ci skip]" || echo "Nothing to commit"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
