name: 定时生成并发行 ros-dpbr-CT-CMCC.rsc

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  release_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Make script executable
        run: chmod +x gen_ros_dpbr.sh

      - name: Run script
        run: ./gen_ros_dpbr.sh

      - name: Create Release and upload rsc file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "auto-$(date +'%Y%m%d')"
          name: "自动发行 $(date +'%Y-%m-%d')"
          files: ros-dpbr-CT-CMCC.rsc
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
